import { NextPage } from 'next';
import Head from 'next/head';

import * as S from './styles';
import { HomeViewPropsInterface } from './view-props.interface';

const HomeView: NextPage<HomeViewPropsInterface> = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <S.Title>
        Welcome to <a href='https://nextjs.org'>Next.js!</a>
      </S.Title>
    </>
  );
};

export default HomeView;
